version: '3.3'
services:
    avm-build-test:
        image: ubuntu-latest
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-3000}:3000'
        environment:
            DB_HOST: 'database'
            DB_USER: 'haskelluser'
            DB_PASSWORD: 'haskellpassword'
            DB_NAME: 'avm'
            JWT_SECRET: 'jwt_secret'
            AVM_PORT: '3000'
            SESSION_TIME: '900'
            AVM_VERSION: '1.0.0'
            AWS_ACCESS_KEY_ID: ''
            AWS_SECRET_ACCESS_KEY: '' 
            AWS_DEFAULT_REGION: 'sa-east-1'
            AWS_S3_BUCKET: 'tiozao-avm'
        volumes:
            - '.:/var/application'
        entrypoint: [ "bash", "-c", "./start-service.sh"]
        depends_on:
            - database
