version: '3.3'
services:
    avm-backend:
        image: avm-backend:1.0
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:3000'
        environment:
            DB_HOST: 'database'
            DB_USER: 'root'
            DB_NAME: 'avm'
            DB_PASSWORD: ''
            JWT_SECRET: 'itookashot'
            AVM_PORT: '3000'
            SESSION_TIME: '900'
            AVM_VERSION: '1.0.0'
        volumes:
            - '.:/var/application'
        entrypoint: [ "bash", "-c", "stack run backend-exe"]
        # entrypoint: [ "bash", "-c", "ghcid --command 'stack ghci app/Main.hs' --test :main"]

    database:
        platform: linux/x86_64
        image: mysql:8.0.33
        command: mysqld --sql_mode=""
        environment:
            MYSQL_DATABASE: 'avm'
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
        - ./schema.sql:/docker-entrypoint-initdb.d/db_structure.sql
        ports:
        - 3306:3306