version: '3.3'
services:
    avm-backend:
        image: avm-backend:1.0
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-3000}:3000'
        environment:
            DB_HOST: 'database'
            DB_USER: 'haskelluser'
            DB_PASSWORD: 'haskellpassword'
            DB_NAME: 'avm'
            JWT_SECRET: 'jwt_secret'
            AVM_PORT: '3000'
            SESSION_TIME: '900'
            AVM_VERSION: '1.0.0'
        volumes:
            - '.:/var/application'
        entrypoint: [ "bash", "-c", "./start-service.sh"]
        depends_on:
            - database

    database:
        platform: linux/x86_64
        image: mysql:5.7
        command: mysqld --sql_mode=""
        environment:
            MYSQL_DATABASE: 'avm'
            MYSQL_USER: 'haskelluser'
            MYSQL_PASSWORD: 'haskellpassword'
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        volumes:
        - ./schema.sql:/docker-entrypoint-initdb.d/db_structure.sql
        ports:
        - 3306:3306