name:                backend
version:             0.1.0.0
github:              "nikalumoglich/avm"
license:             BSD3
author:              "Andre Mesquita"
maintainer:          "nikal.umoglich@gmail.com"
copyright:           "2023 Andre Mesquita Pereira"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/backend#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies: 
    - scotty
    - aeson
    - mysql-simple
    - password
    - text
    - bytestring
    - jwt
    - time
    - containers
    - scientific
    - wai
    - warp
    - http-types
    - hint
    - exceptions
    - amazonka
    - amazonka-s3
    - base
    - conduit-extra
    - lens
    - resourcet

executables:
  backend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backend

tests:
  backend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backend
    - hspec
    - QuickCheck
    - text
    - mysql-simple
    - jwt
    - time
    - containers
    - scientific
    - hspec-wai
    - hspec-wai-json
    - hspec-core
    - wai
    - warp
    - wai-extra
    - http-types
    - bytestring
    - HUnit
    - call-stack
    - http-types
    - aeson
    - utf8-string
    - hint
    - exceptions
